title: FISSION
logo: https://images.spade.builders/uploads/upload_55c7620948a74acb1228d308491e3439.png # transparent FISSION logo + black text
email: hello@spade.builders
description: >- # this means to ignore newlines until "baseurl:"
  FISSION powers microservices for Web3.
home: Powering Web3 # Used to over ride "home" as page title
baseurl: ""
url: "https://fission.codes"
twitter_username: FISSIONcodes
github_username:  FISSION-Suite
github: https://github.com/fission-suite/fission-codes-web

permalink: /:title/

icon: https://images.spade.builders/uploads/upload_4b96958ac61e2564e2c971617bb14b29.png
favicon: https://images.spade.builders/uploads/upload_f869681e203060e3b678589f016f9bc9.png
social: https://images.spade.builders/uploads/upload_4b893e90998a6582393ad40a7c0de5dd.png # FISSION white background

#collections:
#  projects:
#    output: true

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "default"
      permalink: /post/:title

excerpt_separator: "<!-- more -->"

exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor", ".bundle", ".sass-cache"]

markdown: kramdown

plugins:
  - jekyll-feed

# THEME: just-the-docs
theme: "just-the-docs"
search_enabled: true
aux_links:
  '<i class="fab fa-github"></i> FISSION Suite':
    - "//github.com/fission-suite"
  '<i class="fab fa-discord"></i> Discord #lobby':
    - "https://discord.gg/daDMAjE"
  '<i class="fab fa-twitter"></i> @FISSIONcodes':
    - "https://twitter.com/FISSIONcodes"

color_scheme: nil